---
- name: "Clean IVRS"
  hosts: cucm
  gather_facts: no
  become: yes
  tasks:
    - name: "Removing Application"
      ios_command:
       commands:
         - conf t
         - application
         - no service rivanaa flash:app-b-acd-aa-3.0.0.2.tcl
         - no service rivanqueue flash:app-b-acd-3.0.0.2.tcl
      tags: 
        - clean